#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/routes/console.php';

use App\Kernel;
use App\Request\ConsoleRequest;
use Dotenv\Dotenv;

$dotenv = Dotenv::createImmutable(__DIR__);
$dotenv->load();

$container = require_once __DIR__ . '/services.php';

$kernel = new Kernel($container);
$request = ConsoleRequest::handle();

$container->bind(ConsoleRequest::class, $request);

try {
    $kernel
        ->handle($request)
        ->send();
} catch (Exception $e) {
    throw $e;
    // TODO: add error handler
}
